## Global Variabel
@BaseUrl = https://pam-2026-ifs23049-proyek1-be.hellhbn.fun:8080

### ---------------------------------------
## Auth
### ---------------------------------------

### 1. Melakukan pendaftaran
# @name PostRegister
POST {{BaseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Rahel",
  "username": "rahelhbn",
  "password": "rahelcantik123"
}

### 2. Masuk ke layanan
# @name PostLogin
POST {{BaseUrl}}/auth/login
Content-Type: application/json

{
  "username": "rahelhbn",
  "password": "rahelcantik123"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 3. Refresh Token
# @name PostRefreshToken
POST {{BaseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "authToken": "{{authToken}}",
  "refreshToken": "{{refreshToken}}"
}

> {%
    client.global.set("authToken", response.body.data.authToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### 4. Keluar dari layanan
# @name PostLogout
POST {{BaseUrl}}/auth/logout
Content-Type: application/json

{
  "authToken": "{{authToken}}"
}

### ---------------------------------------
## Users
### ---------------------------------------

### 5. Mengambil informasi akun
# @name GetUserMe
GET {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

> {%
    client.global.set("userId", response.body.data.user.id);
%}

### 6. Mengubah informasi akun
# @name PutUserMe
PUT {{BaseUrl}}/users/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Rahel Update",
  "username": "rahelhbn"
}

### 7. Mengubah kata sandi akun
# @name PutUserMePassword
PUT {{BaseUrl}}/users/me/password
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "password": "rahelcantik123",
  "newPassword": "rahelcantik123"
}

### 8. Mengubah foto profil
# @name PutUserMePhoto
PUT {{BaseUrl}}/users/me/photo
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./uploads/examples/me.png
--WebAppBoundary--

### 9. Mengambil foto profil
# @name GetMyPhoto
GET {{BaseUrl}}/images/users/{{userId}}
Content-Type: application/json

### ---------------------------------------
## Books
### ---------------------------------------

### 10. Mengambil semua buku
# @name GetBooks
GET {{BaseUrl}}/books?search=&genre=&is_read=&page=1&perPage=10
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 11. Mengambil statistik buku
# @name GetBookStats
GET {{BaseUrl}}/books/stats
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 12. Menambahkan buku
# @name PostBook
POST {{BaseUrl}}/books
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Laskar Pelangi",
  "author": "Andrea Hirata",
  "description": "Novel tentang perjuangan anak-anak Belitung dalam menggapai pendidikan.",
  "genre": "Fiksi",
  "isbn": "978-979-1073-07-5",
  "publisher": "Bentang Pustaka",
  "year": 2005,
  "isRead": false
}

> {%
    client.global.set("bookId", response.body.data.bookId);
%}

### 13. Mengambil buku berdasarkan ID
# @name GetBookById
GET {{BaseUrl}}/books/{{bookId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 14. Mengubah data buku
# @name PutBook
PUT {{BaseUrl}}/books/{{bookId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Laskar Pelangi",
  "author": "Andrea Hirata",
  "description": "Novel tentang perjuangan anak-anak Belitung dalam menggapai pendidikan.",
  "genre": "Fiksi",
  "isbn": "978-979-1073-07-5",
  "publisher": "Bentang Pustaka",
  "year": 2005,
  "isRead": true
}

### 15. Mengubah cover buku
# @name PutBookCover
PUT {{BaseUrl}}/books/{{bookId}}/cover
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./uploads/examples/me.png
--WebAppBoundary--

### 16. Mengambil cover buku
# @name GetBookCover
GET {{BaseUrl}}/images/books/{{bookId}}
Content-Type: application/json

### 17. Menghapus buku
# @name DeleteBook
DELETE {{BaseUrl}}/books/{{bookId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json